language: node_js
node_js:
  - "node"
# after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - postgresql
before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'pw123';" -U postgres
  - psql -c "ALTER DATABASE travis_ci_test OWNER TO test;" -U postgres
