language: node_js
node_js:
  - "node"
# after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
